MetaMask/keyring-api

- package.json
- yarn.lock
Downgrade to previous Flask version.
> chore(deps): downgrade snaps dependencies to `0.35.2-flask.1`

- src/json-rpc-request.test.ts
- src/json-rpc-request.ts
- src/keyring-api.ts
- src/keyring-internal-api.ts
- src/keyring-rpc-dispatcher.test.ts
- src/keyring-rpc-dispatcher.ts
This PR moves the `JsonRpcRequest` and `JsonRpcRequestStruct` definitions to their own file.
> feat: move `JsonRpcRequest` to its own file

- src/KeyringClient.test.ts
- src/KeyringClient.ts
- src/KeyringSnapControllerClient.test.ts
- src/KeyringSnapRpcClient.test.ts
- src/api.ts
- src/internal-api.ts
This is a **breaking change**.
This PR changes the `KeyringAccount` type to make `options` a mandatory field (non-nullable).
> feature: make `options` a mandatory field of `KeyringAccount`

- src/KeyringClient.test.ts
- src/KeyringSnapControllerClient.test.ts
- src/KeyringSnapRpcClient.test.ts
- src/api.ts
- src/rpc-handler.test.ts
BREAKING CHANGE: This commit renames a field of the KeyringAccount class, making it incompatible with previous versions.
> refactor: rename `supportedMethods` to `methods`

- src/api.ts
BREAKING CHANGE: This PR changes the allowed types of an account.
> fix: rename `erc4337` -> `eip4337`

- src/KeyringSnapControllerClient.test.ts
- src/KeyringSnapControllerClient.ts
This PR adds the `getController` method to the `KeyringSnapControllerClient` class.
> feat: add `getController` to client

- src/api.ts
Rationale: we shouldn't expect keyrings to broadcast transactions, only to sign them.
BREAKING CHANGE: This commit removes the `eth_sendTransaction` from the allowed methods.
> feat: remove `eth_sendTransaction` method

- package.json
- yarn.lock
This PR replaces:
- https://github.com/MetaMask/keyring-api/pull/45
- https://github.com/MetaMask/keyring-api/pull/38
> chore(deps): bump `@metamask/snaps-*` to 0.36.0-flask.1

- src/KeyringClient.test.ts
- src/KeyringClient.ts
- src/KeyringSnapControllerClient.test.ts
- src/KeyringSnapRpcClient.test.ts
- src/api.ts
- src/internal-api.ts
- src/rpc-handler.test.ts
- src/rpc-handler.ts
BREAKING CHANGE: This commit changes the `KeyringAccount` type and the `Keyring` interface.
> feat: remove account name from `KeyringAccount` type

- src/api.ts
BREAKING CHANGE: This PR removes previously supported versioned `eth_signTypedData` methods. Those methods existed because they were implemented before EIP-712 was final.
> feat: remove versioned `eth_signTypedData` methods

- src/api.ts
- src/rpc-handler.test.ts
- src/rpc-handler.ts
This PR makes the `approveRequest` and `rejectRequest` methods optional in the Keyring API.
Rationale: Keyrings that implement a synchonous signature flow don't require those methods to be implemented.
> feat: make `approveRequest` and `rejectRequest` optional

- src/api.ts
- src/rpc-handler.test.ts
- src/rpc-handler.ts
The async transaction flow shouldn't require snaps to implement the `listRequests` and `getRequest` methods, so we are making them optional.
Also, the `exportAccount` may not be supported by all snaps, so it doesn't make sense to force its implementation.
We decided to keep the CRUD account management methods mandatory, since they are (or will be) directly called by MetaMask.
> refactor: make `exportAccount`, `listRequests` and `getRequest` optional

- src/KeyringClient.test.ts
- src/api.ts
This new field should allow snap keyrings that implement the async flow to redirect users to a dapp to continue the transaction signature. This is specially useful for MPC keyrings, since they require some interaction with other participants to sign the transaction.
> feat: add a `redirect` field to asynchronous request responses

- .yarnrc.yml
- package.json
- src/events.ts
- src/internal/events.test.ts
- src/internal/events.ts
- src/snap-utils.test.ts
- src/snap-utils.ts
- yarn.lock
The events added by this PR are intended to replace the existing `snap_manageAccount` methods. Events are more semantically correct, as the keyring's role is to notify the Keyring Controller/Bridge specifically about events related to accounts and requests.
Additionally, this PR introduces a helper function that enables snaps to emit these events.
> feat: add keyring events and helper functions

- src/internal/types.test.ts
- src/internal/types.ts
Changes to the Internal Account: 
- Makes keys in the snap object mandatory 
- Moves the name key from the snap object to metadata
> fix: update snap object keys to be mandatory and move name to metadata

- src/KeyringClient.test.ts
- src/api.ts
- src/rpc-handler.test.ts
BREAKING: This is a breaking API change.
> feat: move request ID to outer request

- src/KeyringClient.test.ts
- src/api.ts
This PR adds an optional `message` field to the snap's response in the async flow.
> feat: add redirection message to snap async response

- src/KeyringClient.ts
Since the `JsonRpcRequest` type is no longer an union, we can use `Omit` from the standard library.
> chore: use `Omit` instead of `OmitUnion`

- src/superstruct.ts
This PR makes the API compatible with `tsc` 4.4.4 by not using the unsupported `import { type ... }` syntax. It also fix linting errors in the same file.
> build: fix linting and compatibility with older tsc

- CHANGELOG.md
- README.md
- docs/architecture.md
- docs/evm_methods.md
Fix some typos and try to be consistent with other [docs](https://support.metamask.io/hc/en-us/articles/4405506066331-User-Guide-Dapps) (i.e. use **Dapp** and **dapp**).
> chore(docs): fix some typos and consistency problems

- src/events.ts
This is more in line with the fact that events are sent to the extension as an RPC call.
```ts
await snap.request({
method: 'snap_manageAccounts',
params: {
method: 'notify:accountCreated',
params: { account },
},
});
```
BREAKING: This is a braking change, but users shouldn't be concerned since it only changes the enum values.
> refactor!: change the events' prefix to `notify:`

- package.json
- src/KeyringSnapControllerClient.test.ts
- src/KeyringSnapControllerClient.ts
- src/KeyringSnapRpcClient.test.ts
- src/KeyringSnapRpcClient.ts
- yarn.lock
This PR moves our clients to use the new `onKeyringRequest` export that Snaps should use to expose the keyring methods.
> feat!: use the `onKeyringRequest` snap export

- src/KeyringClient.ts
- src/internal/index.ts
- src/internal/rpc.ts
- src/rpc-handler.test.ts
- src/rpc-handler.ts
For clarity, this PR moves the internal RPC methods to `internal/rpc.ts`.
> refactor: move internal RPC methods to `rpc.ts`

- src/internal/api.ts
- src/rpc-handler.test.ts
This PR fixes the types of some IDs used in the internal API.
> fix: use `UuidStruct` for IDs in the internap API

- docs/security.md
This new guideline should be used to prevent unsanitized errors from revealing sensitive information to dapps or MetaMask.
> docs: add guideline to sanitize errors

- src/internal/api.ts
- src/rpc-handler.test.ts
The current API forces the ID of the JSON-RPC requests to be a UUIDv4, which is not compliant with the official JSON-RPC specs. Note, however, that this constraint doesn't have an impact on devs who use the Keyring clients, such as `KeyringSnapRpcClient` and `KeyringSnapControllerClient`.
This PR removes this limitation and allows the request ID to be any string, number or null.
Fixes #154
> fix: allow the request ID to be a string, number or null

- src/rpc-handler.test.ts
- src/utils.ts
This PR updates `UuidStruct` to use a named type (`UuidV4`).
> feat: define `UuidStruct` as a named type

- jest.config.js
This PR enables the lcov report exporter available in Jest, it makes easier to use some code coverage tools.
> test: enable lcov report exporter

- README.md
This PR updates MetaMask's version that ships the Keyring API and adds a workaround to a GitHub rendering bug.
See: https://github.com/github/markup/issues/1734
> docs: update MetaMask version and remove admonitions

- package.json
- src/KeyringSnapControllerClient.test.ts
- src/KeyringSnapControllerClient.ts
- src/snap-utils.ts
- yarn.lock
- The versions of `@metamask/snaps-controllers` and `@metamask/snaps-rpc-methods` that this package uses rely on `@metamask/snaps-ui`, which has recently been deprecated. The deprecation causes the dependencies audit on the extension to fail.
- Global objects have been moved out of `@metamask/snaps-rpc-methods` to `@metamask/snaps-sdk`. Specifically, `SnapsGlobalObject` was renamed to `SnapsProvider`.
Given these changes, this commit bumps `@metamask/snaps-controllers` and replaces `@metamask/snaps-rpc-methods` with `@metamask/snaps-sdk`, using `SnapsGlobalObject` instead of `SnapsProvider`.
> Remove @metamask/snaps-ui from dependency tree

- package.json
- yarn.lock
- deps: `@metamask/providers@^13.0.0->^14.0.1`
- deps: bump `@metamask/snaps-` packages to latest
This is a breaking change due to the update of `@metamask/providers`: https://github.com/MetaMask/providers/releases/tag/v14.0.0
Consolidating updates into a single PR in order to not create duplication with incompatible versions of `extension-port-stream`.
---
- #183
> deps: bump @metamask/providers to v14; bump @metamask/snaps packages to latest

- docs/diagrams/user_operation_signing.puml
- docs/evm_methods_userOp.md
- src/eth/erc4337/types.ts
This PR update the docs and adds new optional return values during the PatchUserOperation.
* Fixes [#260](https://app.zenhub.com/workspaces/metamask-accounts-team-v2-64c91cbeaa9d1c00126621fd/issues/gh/metamask/accounts-planning/260)
> feat: update `eth_patchUserOperation` to return optional gas limit values

- docs/evm_methods_userOp.md
As it was, it seemed that there were two levels of arrays, which didn't match the example.
> docs: update `eth_prepareUserOperation` argument to not be an array

- docs/evm_methods_userOp.md
This change just adds a minor note to clarify the need of having `dummySignature` and `dummyPaymasterAndData` as part of the response of `eth_prepareUserOperation`.
> docs: add note to `eth_prepareUserOperation` method response

- src/eth/erc4337/types.test.ts
- src/eth/erc4337/types.ts
- src/eth/types.test.ts
- src/eth/types.ts
- src/superstruct.ts
This PR adds validation for the bundler url returned in the `PrepareUserOperation` step. Prior to this PR, the bundler value accepts any string. 
* Fixes [#289](https://github.com/MetaMask/accounts-planning/issues/289)
> fix: bundler URL validation

- package.json
- yarn.lock
This PR bumps @metamask/snaps-sdk to ^3.1.1
> Bump snaps-sdk version

- src/contexts.ts
- src/index.ts
- src/internal/eth/EthKeyring.ts
Adding an additional parameter about the "execution context" (contains only `chainId` for now) for User operations methods. This will also help computing the CAIP-2 scope/chain-id for underlying calls later on.
> feat!: add KeyringExecutionContext to user ops methods

- src/superstruct.ts
This PR defines the string type in UrlStruct, without it, the type definition sets it as unknown
> fix: bundler type

- .github/workflows/stale.yml
This pull request adds a stale workflow to automatically close stale issues and pull requests. The workflow runs on a schedule and checks for issues and pull requests that have been open for 30 days with no activity. If an issue or pull request is found to be stale, a comment is added with a warning message. If the stale label or comment is not removed within 7 days, the issue or pull request will be automatically closed.
> ci: add stale workflow to close issues and PRs

- package.json
- yarn.lock
Avoid declaring a version for `@metamask/providers` and use the one coming with the `snaps-sdk`.
For now the latest version of providers is `16.0.0`, so we use a quite "wide" opened range that should be enough until the next major bump of the providers.
> refactor: use @metamask/providers as a peer dependency

- docs/architecture.md
- docs/diagrams/user_operation_signing.puml
- docs/evm_methods_userOp.md
This method takes the `callData` as input and returns the transaction intents that were encoded in it.
> docs: add `eth_decodeUserOperationCallData` to documentation

- src/internal/types.test.ts
- src/internal/types.ts
This pull request adds a new property, importTime, to the metadata of the InternalAccount struct. This property will store the import time of the account.
Resolves: 
#288
> Breaking: Add importTime property to InternalAccount metadata

- package.json
- src/api.ts
- src/btc/index.ts
- src/btc/types.test.ts
- src/btc/types.ts
- src/index.ts
- src/internal/types.test.ts
- src/internal/types.ts
- yarn.lock
This PR needs to be merged first:
This adds a new account type for `bip122` family.
> feat: add bip122:p2wpkh account support

- docs/btc-methods.md
- docs/evm-methods.md
- src/btc/types.ts
This PR documents the new `btc_sendmany` method that can be supported by Snaps to sign and broadcast Bitcoin transactions.
> docs: add `btc_sendmany` method

- src/eth/types.test-d.ts
- src/eth/types.ts
This pull request removes the signTransaction method from the EthErc4337Account since it cannot sign transactions.
> fix: remove signTransaction from EthErc4337Account

- package.json
- yarn.lock
This pull request updates the snaps-sdk dependency to version 4.2.0.
> chore(deps): bump snaps-sdk to 4.2.0

- src/internal/events.ts
This PR adds an `accountNameSuggestion` field to the `AccountCreatedEvent` to allow the keyring (Snap) to make a suggestion for how the account should be named. 
MetaMask is responsible for allowing the user to accept or modify the proposed name.
The Snap can call:
```typescript
await this.#emitEvent(KeyringEvent.AccountCreated, {
account,
accountNameSuggestion: "My Account",
});
```
> feat: add `accountNameSuggestion` field to the `AccountCreatedEvent`

- src/eth/types.test-d.ts
- src/eth/types.ts
> fix: keep all ETH methods in the same `enum`

- src/api.ts
- src/eth/utils.ts
> fix: don't use internal types in the public API

- package.json
- yarn.lock
`@metamask/providers` v17 has been released.
This extends the `peerDependency` range to allow using the new version on to pof already supported versions.
Also bumps `devDependencies` versions to replace usage of `@metamask/providers@16` with `@metamask/providers@17`.
> feat: support @metamask/providers v17

- src/api/account.ts
- src/api/keyring.ts
- src/rpc-handler.test.ts
- src/rpc-handler.ts
This change will allow accounts to have multiple addresses, for multiple chains.
Fixes: https://github.com/MetaMask/accounts-planning/issues/464
> feat: allow multiple address per account

- src/api/account.ts
- src/api/keyring.ts
- src/rpc-handler.test.ts
- src/rpc-handler.ts
This reverts commit `f6b3701eb0d9acbb99cff244f18d885eaacc32e6` ([#315](https://github.com/MetaMask/keyring-api/pull/315)).
> Revert "feat: allow multiple address per account (#315)"

- package.json
- src/JsonRpcRequest.test.ts
- src/JsonRpcRequest.ts
- src/KeyringClient.ts
- src/api/account.test.ts
- src/api/account.ts
- src/api/balance.ts
- src/api/caip.ts
- src/api/export.ts
- src/api/request.ts
- src/api/response.ts
- src/btc/types.ts
- src/eth/erc4337/types.test.ts
- src/eth/erc4337/types.ts
- src/eth/types.ts
- src/internal/api.ts
- src/internal/events.test.ts
- src/internal/events.ts
- src/internal/types.test.ts
- src/internal/types.ts
- src/rpc-handler.ts
- src/superstruct.test-d.ts
- src/superstruct.test.ts
- src/superstruct.ts
- src/utils/types.test.ts
- src/utils/types.ts
- yarn.lock
Replaces: <https://github.com/MetaMask/keyring-api/pull/328>
> chore: migrate to `@metamask/superstruct` and update required dependencies

- package.json
- yarn.lock
Aligns dependency versions with sibling packages to fix/prevent build errors caused by nested dependency version mismatch:
- e.g. https://github.com/MetaMask/snaps/actions/runs/9720788583/job/26900545288?pr=2445
```md
- Bump `@metamask/snaps-sdk` from `^6.0.0` to `^6.1.0` ([#358](https://github.com/MetaMask/keyring-api/pull/358))
```
- https://github.com/MetaMask/core/pull/3645
- https://github.com/MetaMask/snaps/pull/2445
> Bump `@metamask/snaps-sdk` from `^6.0.0` to `^6.1.0`

- .github/workflows/create-release-pr.yml
Bumps the `create-release-pr` GitHub action to v3.
**BREAKING CHANGE:** Formats the changelog using Prettier.
> ci: bump 'MetaMask/action-create-release-pr' from v2 to v3
